baseURL = "https://firesafety-py.netlify.com/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
theme = "compose"
title = "Compose Docs"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 2
[[menu.main]]
name = "Docs"
url = "docs/"
weight = 1
[params]
author = "Weru"
repo = "https://github.com/onweru/compose"
searchPlaceholder = "Search the docs ..."
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
[params.source]
icon = "github.svg"
name = "GitHub"
url = "https://github.com/onweru/compose/"
