name = "firesafety"
license = "MIT"
licenselink = "https://github.com/onweru/compose/blob/master/LICENSE"
description = "A hugo theme for documentation sites. It's inspired by forestry.io's docs page"
homepage = "https://firesafety-py.netlify.com/"
tags = ["simple", "docs"]
features = ["docs", "search"]
min_version = "0.53.0"

[author]
  name = "Weru"
  homepage = "https://github.com/onweru"
