name = "Compose"
license = "MIT"
licenselink = "https://github.com/google/compose/blob/master/LICENSE"
description = "A Hugo theme for technical documentation sites"
homepage = "https://compose.netlify.com"
tags = ["documentation", "simple", "customizable", "responsive", "docs"]
features = []
min_version = 0.53

[author]
  name = "Weru"
  homepage = "https://compose.netlify.com"
